version = 1
SPDX-PackageName = "TODO"
SPDX-PackageSupplier = "TODO"
SPDX-PackageDownloadLocation = "https://github.com/etallab/TODO"

[[annotations]]
path = [ "flake.nix", "flake.lock", "pyproject.toml", "CITATION.cff" ]
SPDX-FileCopyrightText = "2026 TODO"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data/**/*"
SPDX-FileCopyrightText = "2026 TODO"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.py"
SPDX-FileCopyrightText = "2026 TODO"
SPDX-License-Identifier = "BSD-3-Clause"